### DISCUSSION TITLE
My experience creating a 100+ mod profile

### DISCUSSION THREAD

**Discussion by xane256** [gorilla-devs/ferium#156] [Show and tell]
Hello, I have been working with another person to put together a mod list for a technical minecraft community. We have assembled a very large modlist by hand with over 100 mods, and I used that info + regex processing to create [this script](https://gist.github.com/xane256/99f57420c4f486c6bba8b2db931aee68) to generate a profile from the mod list. I thought I'd share my experience creating the profile with those mods. Several mods had issues that could be fixed by the fallback feature I posted (#155). My goal is to construct a "master" modlist for part of the technical minecraft community and I want to use ferium to help people install whatever subset of mods they want, instead of passing around a large untrusted zip file. I think a lot of people in that community would appreciate the collection of mods and I'm really excited that ferium is by far the best way for people to share and download all those mods.

I want to highlight some of the difficulty I've encountered as an anecdotal example or "sample workflow" of the process of making a large profile. I don't know how heavily other people use ferium for custom modpacks but I hope sharing this process can be helpful. My workflow involves running the script within a [docker container](https://gist.github.com/xane256/26f662d24dd9c3b32cbab9ce1bdffc5d) setup that I made.

The list below shows the issues I had with each mod that were not easily fixable by ignoring the mod loader. For each mod in the list, I have already considered using a different platform but most are github exclusive; mods that were easy to add by changing platform are not in this list at all. The yaml at the bottom shows a summary of all the mods I had to address including what kind of change would allow ferium to get the right version of the mod.

**Errors obtaining files from github**
- `gnembon/carpet-autoCraftingTable`
  - mod is outdated and cannot be added
  - workaround: Downgrade profile game version, add, then switch game version again. Otherwise manually edit config.
  - Ideal fix: resolve #142
- `RedLime/SleepBackground`
  - only available on github
  - workaround (for 1.18.2): ignore loader and version. Ferium will correctly download the "1.14+" version because it is first in the list
  - Ideal fix: add option `--fallback=url --fallback-url=https://github.com/RedLime/SleepBackground/releases/download/2.3/sleepbackground-2.3+1.14+.jar`
- `FakeDomi/FastChest`
  - CurseForge [page](https://www.curseforge.com/minecraft/mc-mods/fastchest) is now deprecated. 1.19+ releases are available through github only
  - workaround (for 1.18.2): use deprecated curseforge releases
  - Ideal fix: add option `--fallback=major` to consider the latest 1.18 major release as compatible for 1.18.x if correct version is not found.
- `A5b84/dark-loading-screen`
  - only available on github
  - releases are not labeled with version numbers. Compatibility is described in this [table](https://github.com/A5b84/dark-loading-screen/blob/main/CHANGELOG.md#compatibility-table)
  - workaround: ~~None, the mod must be downloaded manually.~~ **Edit**: Switched to CurseForge releases
  - Ideal fix: add option `--fallback=url --fallback-url=https://github.com/A5b84/dark-loading-screen/releases/tag/v1.6.11`
- `NoFog`
  - CF Project [296468](https://www.curseforge.com/minecraft/mc-mods/nofog)
  - The operation fails because "The developer of this mod has denied third party applications from downloading it".
  - The actual issue is the mod incorrectly lists [legacy cloth config](https://www.curseforge.com/minecraft/mc-mods/cloth-config-legacy) as dependency which cannot be downloaded.
  - The console provides no indication that this fact is the issue. It prompts to ask if you'd like to install the optional dependencies Fabric API and ModMenu, but does not print anything about "cloth" when it gives an error.
  - Using the flag `--dont-add-dependencies` does not work. In fact, `ferium add 319057 --dont-add-dependencies` prints nothing except the error which is highly misleading because "this mod" does not apply to NoFog.
  - workaround: None, the mod must be downloaded manually.
  - Ideal fix: Improve clarity of errors and fix issue #152
- `Chat Up`
  - CF Project [367561](https://www.curseforge.com/minecraft/mc-mods/chat-up)
  - outdated, same thing as #142 again
- `Music Duration Reducer`
  - CF Project [400131](https://www.curseforge.com/minecraft/mc-mods/music-duration-reducer)
  - same issue as `NoFog`
  - workaround: None
- `Coow/Cows-Odd-Widgets`
  - Fails because version is not in filename. However, the versino is in the release name.
  - workaround: None. Must downlaod manually unless profile is for the latest mod release version (1.18.2). When they release 1.19 version that will break too.
  - Ideal fix: apply version checking to GH release names
- `multiconnect`
  - Skips version 1.18.2, supports 1.19. Impossible to know what correct decision is for 1.18.2 without testing launching the game.
  - Same #142 issue
- `invview`
  - Skips 1.18.2, supports 1.19.
- `Reload Audio Driver`
  - CF project [391502](https://www.curseforge.com/minecraft/mc-mods/reload-audio-driver-fabric)
  - version label is 1.18.1 but filename says 1.18.x.
  - workaround: None. The game supports 1.19 so ignoring game version does not work.
  - Ideal fix: use `fallback: previous` or `fallback: minor` option from fallback suggestion
- `item-model-fix`
  - CF Project [399798](https://www.curseforge.com/minecraft/mc-mods/item-model-fix)
  - blocked dependency issue

```yml
changes:
# mods that could not be added because they are not up to date:
- mod: cf/chat-up
  key: 367561
  change: old
- mod: mr/multiconnect
  change: old
- mod: mr/invview
  change: old
- mod: gnembon/carpet-autoCraftingTable
  change: old

# Mods that would improve from fallback options
- mod: cf/reload-audio-driver-fabric
  key: 391502
  change: {fallback: previous}
- mod: RedLime/SleepBackground
  change: {fallback: latest}
- mod: FakeDomi/FastChest
  change: {fallback: major}
- mod: A5b84/dark-loading-screen
  change: {fallback: url} # Update: Available on CurseForge

# Mods that have a broken dependency
- mod: cf/item-model-fix
  key: 399798
  change: dependency
- mod: cf/NoFog
  key: 296468
  change: dependency
- mod: cf/music-duration-reducer
  key: 400131
  change: dependency

# Mods that work fine as soon as the loader is ignored
- mod: chiraagChakravarthy/SubTick
  change: loader
- mod: whoImT/carpet-addons
  change: loader
- mod: Super-Santa/EssentialAddons
  change: loader
- mod: plusls/plusls-carpet-addition
  change: loader
- mod: fxmorin/MemoryLeakFix
  change: loader
- mod: fxmorin/MoreCulling
  change: loader

# Mods where ferium could not determine version
- mod: Coow/Cows-Odd-Widgets
  change: fix-version

```

**Issues I would raise based on this**:
- Some mods have no workaround and must be downloaded manually. Sometimes this is because ferium cannot determine which version to use, but [NoFog](https://www.curseforge.com/minecraft/mc-mods/nofog) for example has perfect version labeling but a deprected dependency. There should be a way to use these mods with ferium even though they have erroneous metadata of some kind.
- Improve clarity of mod additions (from user or dependency) that give errors. For example, print the mod name before the error. My workaround for this was to add print statements to the shell script I was using, but that did not help for the dependency errors.
- Adding mods with broken dependencies fails with no explanation of the cause
- Cow's odd widgets doesn't find the right version

**Features I would suggest to make this easier**
- Most github repos only host a single mod for a single mod loader. Consider `--dont-check-mod-loader` for github by default.
- Add the fallback version options (#155)
- Improve handling of mods with broken dependencies by listing the broken dependencies, or adding the mod in a disabled / incompatible state.
- Consider allowing `--dont-add-dependencies` to ignore required dependencies. I'm not sure this is the right choice in general but it would have been
  essentially the only workaround for a few mods here.
- Allow adding incompatible mods that don't download anything during `ferium upgrade`, including:
  - old mods which are not updated yet
  - mods which have unmet and un-added dependenceis
- Don't print "The mod has already been added" as an error. When running the script multiple times for checking compatibility it is distracting to see those messages for almost every mod.
