### ISSUE TITLE
The Rustfmt.toml does not match the code

### ISSUE THREAD

**Issue by tippfehlr** [gorilla-devs/ferium#285]
from `Rustfmt.toml`:
```toml
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
```
but in the code they are not applied (see [`src/cli.rs`](../tree/main/src/cli.rs))
